# Build
set(CMAKE_BUILD_TYPE Release)

# Options
set(SEGMENT_TREE_BENCHMARKS
    ON
    CACHE BOOL "" FORCE)

set(SEGMENT_TREE_EXAMPLES
    ON
    CACHE BOOL "" FORCE)

set(SEGMENT_TREE_TESTS
    ON
    CACHE BOOL "" FORCE)
