name: cmake_integration_tests

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

    # add_subdirectory
      - name: Configure add_subdirectory
        run: cmake -S tests/cmake_integration_tests/add_subdirectory -B .add_subdirectory_build

      - name: Build add_subdirectory
        run: cmake --build .add_subdirectory_build --parallel 8

    # fetch_content
      - name: Configure fetch_content
        run: cmake -S tests/cmake_integration_tests/fetch_content -B .fetch_content_build

      - name: Build fetch_content
        run: cmake --build .fetch_content_build --parallel 8

    # find_package
      - name: Configure segment_tree
        run: cmake -S . -B .build

      - name: Build segment_tree
        run: cmake --build .build --parallel 8

      - name: Install segment_tree
        run: cmake --install .build --prefix .build/install

      - name: Configure find_package
        run: cmake -S tests/cmake_integration_tests/find_package -B .find_package_build

      - name: Build find_package
        run: cmake --build .find_package_build --parallel 8
