name: main

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cxx: [clang++-6.0, clang++-8, clang++-9, g++-7, g++-8, g++-9]
        include:
          - os: macos-latest
            cxx: clang++
          - os: windows-latest
            cxx: msvc

    runs-on: ${{ matrix.os }}

    env:
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -S . -B .build

      - name: Build
        run: cmake --build .build --parallel 8

      - name: Test
        run: (cd .build && ctest --output-on-failure)
