name: main

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        tool: [
          linux_clang6,
          linux_clang8,
          linux_clang9,
          linux_clang9_asan,
          linux_clang9_lsan,
        # linux_clang9_msan,
          linux_clang9_tsan,
          linux_clang9_ubsan,
          linux_gcc7,
          linux_gcc8,
          linux_gcc9]
        include:
          - os: macos-latest
            tool: macos_clang
          - os: windows-latest
            tool: windows_msvc

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -S . -B .build -DCMAKE_TOOLCHAIN_FILE="toolchain/${{ matrix.tool }}.cmake"

      - name: Build
        run: cmake --build .build --parallel 8

      - name: Test
        run: (cd .build && ctest --output-on-failure)
