#
# Copyright (C) 2020 Ruslan Manaev (manavrion@gmail.com)
# This file is part of the segment_tree header-only library.
#

# Project information
site_name: Segment tree
site_url: https://manavrion.github.io/segment_tree/
site_author: Ruslan Manaev
site_description: A generic segment tree C++ header-only library.

# Repository
repo_name: manavrion/segment_tree
repo_url: https://github.com/manavrion/segment_tree
edit_uri: https://github.com/manavrion/segment_tree/edit/master/mkdocs/docs/

# Copyright
copyright: Copyright &copy; 2020 Ruslan Manaev

# Configuration
theme:
  name: material
  features:
    - instant
    - tabs
  palette:
    scheme: slate
  icon:
    logo: fontawesome/brands/github-alt

# Customization
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manavrion

# Page tree
nav:
  - Home:
    - index.md
  - Examples:
    - examples/examples.md
  - Paper:
    - paper/paper.md

# Extensions
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:
