site_name: Segment tree

edit_uri: edit/master/mkdocs/docs/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - instant
    - tabs
  icon:
    logo: fontawesome/brands/github-alt

nav:
  - Home:
    - index.md
  - Examples:
    - examples/examples.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manavrion
